import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

const client = new Client({ name: "slide-master-picker-smoke", version: "1.0.0" });
const transport = new StreamableHTTPClientTransport(new URL("http://127.0.0.1:3000/mcp"));
await client.connect(transport);
const tools = await client.listTools();
const openTool = tools.tools.find((t) => t.name === "open_slide_master_template_picker");
console.log("TOOLS", tools.tools.map((t) => t.name).join(","));
console.log("TOOL_UI", openTool?._meta?.ui?.resourceUri || "", openTool?._meta?.["openai/outputTemplate"] || "");
const purpose = "삼성전자서비스 미래 대응 전략";
const picker = await client.callTool({ name: "open_slide_master_template_picker", arguments: { purpose, recommendation_limit: 6 } });
const sc = picker.structuredContent || {};
console.log("PICKER", sc.selectable_total, sc.shortlist?.length, sc.shortlist?.[0]?.id, sc.presets?.length, sc.payload_ready, sc.host_ui_rendered);
const ui = await client.readResource({ uri: "ui://slide-master/template-picker-v1.html" });
const resource = ui.contents?.[0] || {};
console.log("UI", resource.text?.length || 0, resource.text?.includes("<script type=\"module\">") === true);
console.log("CSP", JSON.stringify(resource._meta?.ui?.csp || null));
const templateId = sc.shortlist?.[0]?.id;
const presetId = sc.presets?.[0]?.id;
const valid = await client.callTool({ name: "validate_slide_master_selection", arguments: { purpose, template_id: templateId, preset_id: presetId } });
console.log("VALIDATE", valid.isError === true ? "ERROR" : valid.structuredContent?.valid, valid.structuredContent?.selection_token || "");
if (valid.isError === true) console.log("VALIDATE_ERROR_DETAIL", JSON.stringify(valid));
if (!openTool || !templateId || !presetId || valid.isError === true || !valid.structuredContent?.selection_token) process.exitCode = 1;
await client.close();
